zeebe:
  client:
    cloud:
      region: lhr-1
      clusterId: 848240b1-573c-4a07-bd52-723bea5b23b7
      clientId: 2IwpE9J_U94SCeW82CQCKNXHCoT3o5.D
      clientSecret: dHLMYTvGqxQACs7cZBYhX32UfMA58nzDr7GmWe0bhoyDw~U-S4aADd7AkNKKaEj2

calendly:
  booking:
    url: https://calendly.com/business-enzojoly/30min

stripe:
  api:
    key: ${STRIPE_SECRET_KEY:}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51R7oYvGdUZ9m46wApAnk6ZnLwXCclARbePEZhOzGQzoGY8dNIglDL9EHe6SM2OzzX3QDh8En1w5k1APRkp6jwZOS00gey9yX9O}

# Create your API key via https://api-ninjas.com/profile
api-ninjas:
  key: 0lrEuA80z4oFM14SD5bYnQ==z2wFXsZKrsJ4R4FR
