zeebe:
  client:
    cloud:
      region: lhr-1
      clusterId: 848240b1-573c-4a07-bd52-723bea5b23b7
      clientId: 2IwpE9J_U94SCeW82CQCKNXHCoT3o5.D
      clientSecret: dHLMYTvGqxQACs7cZBYhX32UfMA58nzDr7GmWe0bhoyDw~U-S4aADd7AkNKKaEj2

# Create your API key via https://api-ninjas.com/profile
api-ninjas:
  key: 0lrEuA80z4oFM14SD5bYnQ==z2wFXsZKrsJ4R4FR